spring.application.name=omniflow

# Configurações do PostgreSQL usando variáveis
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5420}/${DB_NAME:omniflow}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estratégia de Nomenclatura
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Controle customizado
app.log.console.enabled=true
app.log.file.enabled=true
app.log.file.path=logs/omniflow.log

# Configuração padrão do Spring para o nível de log
logging.level.root=INFO
logging.level.br.com.pc.omniflow=DEBUG